// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNjSAjqcIMxgrL7mE3EgjOP3dtvYSo-0k',
    appId: '1:170071540800:web:4ed3c331756d53661ccba5',
    messagingSenderId: '170071540800',
    projectId: 'project365-d93e1',
    authDomain: 'project365-d93e1.firebaseapp.com',
    storageBucket: 'project365-d93e1.appspot.com',
    measurementId: 'G-D4B441V559',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATMBTNCk73wudjloLxQ-HZ0Zv74AKB9ic',
    appId: '1:170071540800:android:8df55d2ae8b09c701ccba5',
    messagingSenderId: '170071540800',
    projectId: 'project365-d93e1',
    storageBucket: 'project365-d93e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkr4QaEiCbgI4b9P5q5YDQVtJnZyI5rUk',
    appId: '1:170071540800:ios:180c0e0192a755191ccba5',
    messagingSenderId: '170071540800',
    projectId: 'project365-d93e1',
    storageBucket: 'project365-d93e1.appspot.com',
    iosClientId: '170071540800-g1svriq9f8dr7jvqafba2v6s68tujcj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1MovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkr4QaEiCbgI4b9P5q5YDQVtJnZyI5rUk',
    appId: '1:170071540800:ios:180c0e0192a755191ccba5',
    messagingSenderId: '170071540800',
    projectId: 'project365-d93e1',
    storageBucket: 'project365-d93e1.appspot.com',
    iosClientId: '170071540800-g1svriq9f8dr7jvqafba2v6s68tujcj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.project1MovieApp',
  );
}
